### ISSUE TITLE
5.3 FAMIS CLOUD: CCS Users Offline Usage

### ISSUE THREAD

**Issue by RobertGuinn** [apptreesoftware/revolution#115]
**Description**

Columbus City School users, after logging in and caching data, frequently go off-line for longer than average periods of time.  They are reporting that when returning to network coverage, they are getting errors when trying to refresh workbenches, they are getting errors when retrieving lists and they have to log out and log in to fix the problem.

Podio: FAMIS 7

**Steps to Reproduce**

User tcarter6 password is in 1pass.

**App ID**

ccs.famis.com

**Version Number**

5.3.12

**Comment by matthewtsmith** [comment]
@alexisandreason This makes me suspect that the AccruentCloud connector is never sending a authorization error (401) when the cookie expires. If it were the client would be logged out automatically. Please test this by logging in and then making a follow up request with a bad cookie. The connector should be responding to calls with a 401 instead of a json response.

**Comment by alexisandreason** [comment]
@matthewtsmith When I make a subsequent request with a bad cookie to the connector, I get a 401 response from the ccs connector.

**Comment by matthewtsmith** [comment]
@alexisandreason is the core then passing that back to the client as a 401? For some reason the client is not thinking the token is expired.

**Comment by alexisandreason** [comment]
@matthewtsmith This has been fixed in pr 1 on the old core. The core was not passing through the status code on error.

**Comment by RobertGuinn** [comment]
@mellissatort  will test 5.3 core update in sandbox on Monday 11/7.

**Comment by alexisandreason** [comment]
@mellissatort @matthewtsmith @RobertGuinn I have copied the revolution database to sandbox and deployed the new core there as well. To access the 53 sandbox portal use http://53sandbox-apptreesoftware.rhcloud.com/portal/index.html

**Comment by mellissatort** [comment]
@sambbaron On the 5.3.13 (1793) iOS client I am trying to connect to sandbox with either of the following app IDs and am getting the error  "Error.  The operation couldn't be completed. (NSURLErrorDomain error -1202.)"

App ID:  vendor.wawa.com or ccsstage.famis.com

**Comment by alexisandreason** [comment]
@mellissatort The environment was pointed at the old 53 sandbox URL. I updated it and am able to get to both of those app IDs. The app logos will not show since production was copied without copying the images folder. Just so you know since it gave me pause when I opened them. The logos are correct in production.

**Comment by mellissatort** [comment]
@RobertGuinn 5.3 core update has been tested in sandbox for vendor.wawa.com and ccsstage.famis.com
