### ISSUE TITLE
Expensive queries

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#134]
Heroku is reporting we have 2 queries causing load:

`SELECT COUNT(*) FROM apptree.atf_connector_request WHERE completed = ? AND type_id = $1 AND cache_suffix = $2 AND start_date >= NOW() - INTERVAL ?`

`SELECT * FROM apptree.atf_data_layer_config WHERE APP_ID = $1 AND VERSION = $2`

We need to check our indexes and query logic to optimize this.

**Comment by RobertGuinn** [comment]
@alexisandreason  Can you tell me what each of these are used for?  

RE: SELECT COUNT(*) FROM apptree.atf_connector_request WHERE completed = ? AND type_id = $1 AND cache_suffix = $2 AND start_date >= NOW() - INTERVAL ?

The count(*) operation is going to be expensive, regardless of the situation.  We have to be very careful about using any count(*) or other summary operations.

First, I want to understand how this is used.  But, for arguments sake, lets say it needs to be exactly as it is.  Here is what you would want to consider.

There are no indexes on this table.  Table has > 100K rows in it so that is a problem.

Evaluating the columns in your where clause:

'completed' is a boolean.  You will not get good performance from a query that LEADS with a boolean (it's the first column in your where clause).  You will want to find something with higher cardinality.

Booleans, given that they can only be 1 of 2 possible values, will have the lowest cardinality of any value and therefore not help with query performance.  Put them at the end and don't index them.

cache suffix is null over 80% of the time so this is also of very little value to index.

Dates are not always great candidates for indexes, but it IS a good candidate for the one in your where clause.  Your where clause is using a >= on a date, so if you index it, it will already be sorted by date which will accelerate this kind of comparison.

Looking at the structure of the query, the type_id is the best place to start.

You would create 2 indexes:

create index atf_connector_request_idx1 on atf_connector_request(type_id);
create index atf_connector_request_idx2 on atf_connector_request(start_date);

then you would reorganize your where clause to enforce a certain order to the execution plan for this query:

SELECT COUNT(*)
  FROM apptree.atf_connector_request
  WHERE type_id = $1
        AND start_date >= NOW() - INTERVAL ?
        AND cache_suffix = $2
        AND completed = ?

But, the real issue here is the count(*) so lets talk about that.

RE: Query #2 

This one is simple.  It's missing an obvious index:

create index apptree.atf_data_layer_config_idx1 on apptree.atf_data_layer_config(app_id, version);

@matthewtsmith  fyi.
