### ISSUE TITLE
Allow user to keep same connector secret when updating connector

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#141]
Right now when I update a connector URL or headers it makes me re-enter the connector secret. If a secret is set it should allow the user to keep the current one or update it.

I would suggest having a radio button toggle 
- Keep Existing Secret
- Update Secret

and only enable the field if -UpdateSecret is picked.

**Comment by matthewtsmith** [comment]
@sambbaron this is not critical but I'm doing a lot of this lately so its pretty cumbersome to go lookup the secret each time. If this can be prioritized I'd appreciate it.

**Comment by sambbaron** [comment]
@matthewtsmith I understand.  That is a pain.  I think we'll need a Core change for this.

@alexisandreason Right now, I only send the `connectorSecret` property when the user has input a secret key.  What if the Core interpreted that to mean "don't update the secret" rather than "set the secret to null"?

**Comment by alexisandreason** [comment]
@matthewtsmith @sambbaron The core will only change the secret if a secret is sent. If it is null then it leaves whatever it already has.

**Comment by sambbaron** [comment]
@matthewtsmith Is that the behavior you are experiencing?  I need to do some UI work on the connector secret.

**Comment by matthewtsmith** [comment]
@sambbaron I don't know if that is what I'm experiencing because I'm unable to press the save button if I don't enter a secret.
