### ISSUE TITLE
Add user password link is invalid when user email is leete@uchc.edu

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#187]
Within the app ID trial.uchc.edu the communication settings have been updated to send emails for testing to leete@uchc.edu and andrew.leete@gmail.com.  When adding a new user the new user email is sent to this configured email address.  However when the recipient clicks on the set password link in the email they receive the response "password request link is invalid".  If we update the test email to mellissa.tort@apptreesoftware.com there are no issues with the link.  The same behavior exists with the reset password email and any communication emails where a link to setup the users account exists.

App ID:  trial.uchc.edu

**Comment by sambbaron** [comment]
@mellissatort If you replicate with developer tools open in the browser, you can see the exact response from the Core.  I am assuming this is a Core bug.

**Comment by alexisandreason** [comment]
@mellissatort  I will have time to look into the error this afternoon.

**Comment by alexisandreason** [comment]
@sambbaron I think this is a portal bug. It only fails when opened in IE. I forwarded you the email that the user forwarded to me. The link is formatted correctly and works when I open it in Safari.

**Comment by sambbaron** [comment]
@mellissatort Can you confirm @alexisandreason take on this issue?  It seems that from your issue description that when you changed the email address to your email that the user was able to open the link.  Were they using Internet Explorer in both cases?  If so, can you find out what version of IE they are using?

**Comment by alexisandreason** [comment]
@sambbaron From @mellissatort 'Andrew Leete with UCHC forwarded you a reset password email he had issues with.  We think we figured out the issue though...  He was opening the link in IE from his email but when he copied the link url and pasted it in Chrome it worked successfully.  so the issue seems to be IE browser related.' I'm not sure which version of IE he was using though.

**Comment by sambbaron** [comment]
@alexisandreason @mellissatort Okay, John and I were just looking at the Portal in IE11 the other day, and there weren't any issues, but we weren't looking at the mobile user reset password page specifically.  Since we are eventually going to have all mobile users reset passwords through the mobile client, my preference would be not to take this issue further if that's okay with you.
