### ISSUE TITLE
WAWA 5.3.12:  Select additional tag on work order and tag detail displays "Unsaved" even though updates not made

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#24]
App ID:  vendor.wawa.com
Version 5.3.12  iOS
Login:  demo3

Select work order 11721657
Add tag and press Submit on parent WO
On parent work order select new tag to view detail
Message at top of form indicated "Unsaved" though no updates made.
Navigate away from work order and not prompted to save/abandon changes.
Return to work order and still indicates "Unsaved".

**Comment by matthewtsmith** [comment]
@mellissatort @RobertGuinn  I investigated this and this is just a bad data issue in the dev environment that we have run into in the past. The problem is the value "EV" is one of the categories but that category does not exist in the DEV lists. @eyuapptree and I have run into this before in vendor.wawa.com
